//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMABasic.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECMABasic.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 PRINT &quot;PROGRAM FILE 1: NULL PRINT AND PRINTING QUOTED STRINGS.&quot;
        ///20 PRINT &quot;    ANSI STANDARD 3.2, 3.4, 5.2, 5.4, 12.2, 12.4&quot;
        ///30 PRINT
        ///40 PRINT &quot;*** NOTE: THIS PROGRAM MAKES USE OF THE END STATEMENT&quot;
        ///50 PRINT &quot;    WHICH HAS NOT YET BEEN TESTED. IF SUBSEQUENT TESTS SHOW&quot;
        ///60 PRINT &quot;    THIS FEATURE TO BE INCORRECTLY IMPLEMENTED, THEN THE &quot;
        ///70 PRINT &quot;    VALIDITY OF THE RESULTS OF THIS TEST ROUTINE IS DOUBTFUL.&quot;
        ///80 PRINT
        ///90 PRINT
        ///100 PRINT &quot;                  * * * * * * * * * * * * * * * * * *&quot;
        ///110 PRINT &quot;    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string P001_BAS {
            get {
                return ResourceManager.GetString("P001_BAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] P001_OK {
            get {
                object obj = ResourceManager.GetObject("P001_OK", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
